spring.application.name=vitrine
server.port=8080

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=vitrine_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=vitrine_user
spring.datasource.password=Vitrine@123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none

#INFORMAÇÕES:

#integratedSecurity: (true) Indica que a Conxeção será feita com as credenciais do windowns (false) Credencial do SQL SERVER
#encrypt: (true) Requer criptografia do Cliente (false) não requer criptografia do Cliente
#TrustServerCertificate: (true) Instrui o aplicativocliente a ignorar a validação do certificado SSL/TSL do servidor